name: devnet-bundle-snapshot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: conterra/devnet-bundle-snapshot-action@v1
