name: devnet-bundle-snapshot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
        with:
            node-version: lts/*
        - name: Install dependencies
        run: npm ci
        - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        - name: Run Playwright tests
        run: npx playwright test
        - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: conterra/devnet-bundle-snapshot-action@main
        with:
            nexus_id: ${{secrets.NEXUS_ID}}
            nexus_user: ${{secrets.NEXUS_USER}}
            nexus_user_pw: ${{secrets.NEXUS_USER_PW}}
            nexus_url: ${{secrets.NEXUS_URL}}
            nexus_url_release: ${{secrets.NEXUS_URL_RELEASE}}
            nexus_url_snapshots: ${{secrets.NEXUS_URL_SNAPSHOTS}}
            release_token: ${{secrets.RELEASE_TOKEN}}
