name: devnet-bundle-release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true
      nextDevVersion:
        description: "Next SNAPSHOT version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: conterra/devnet-bundle-release@v1.0.0
       with:
         releaseVersion: ${{ github.event.inputs.releaseVersion }}
         nextDevVersion: ${{ github.event.inputs.nextDevVersion }}
