name: SNAPSHOT

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

env:
  ARTIFACT_ID: mapapps-remote-project-blueprint
  VERSION: 4.11.1-SNAPSHOT

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          repositories: >
            [
              {
                "id": "central",
                "url": "http://central",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          plugin_repositories: >
            [
              {
                "id": "central",
                "url": "http://central",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          servers: >
            [
              {
                "id": "${{ secrets.NEXUS_ID }}",
                "username": "${{ secrets.NEXUS_USER }}",
                "password": "${{ secrets.NEXUS_USER_PW }}"
              }
            ]
          mirrors: >
            [
              {
                "id": "${{ secrets.NEXUS_ID }}",
                "mirrorOf": "central",
                "url": "${{ secrets.NEXUS_URL }}"
              }
            ]
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn prepare-package -Prun-js-tests,include-mapapps-deps
      - name: Publish to Nexus
        run: mvn deploy -Pcompress -Dmaven.test.skip.exec=true -Ddist.releases.id=${{ secrets.NEXUS_ID }} -Ddist.releases.url=${{ secrets.NEXUS_URL_RELEASE }} -Ddist.snapshots.id=${{ secrets.NEXUS_ID }} -Ddist.snapshots.url=${{ secrets.NEXUS_URL_SNAPSHOTS }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/${{ env.ARTIFACT_ID }}-bundle.zip,target/${{ env.ARTIFACT_ID }}-sample-app.zip"
          preRelease: true
          allowUpdates: true
          tag: ${{ env.VERSION }}
          token: ${{ secrets.RELEASE_TOKEN }}
